apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-hello
  labels:
    app: spring-boot-hello
  namespace: playground
  annotations:
    flux.wave.works/automated: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-hello
  template:
    metadata:
      labels:
        app: spring-boot-hello
    spec:
      containers:
        - name: spring-cloud-discovery
          image: naresh240/spring-boot-hello:v2
