kind: Service
apiVersion: v1
metadata:
  name: spring-boot-hello-nodeport
spec:
  type: NodePort
  selector:
    app: spring-boot-hello
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30001
